development:
  adapter: postgresql
  database: etsy_manager_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: etsy_manager_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: etsy_manager_production
  pool: 5
  timeout: 5000
